version: "3.9"
services:

  postgres:
    image: postgres:14.1-alpine
    expose:
      - "5432"
    volumes:
      - vpostgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: thedbname
      POSTGRES_USER: thedbuser
      POSTGRES_PASSWORD: thedbpwd
    networks:
      - ndockerdjango
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  djangoproject:
    depends_on:
      postgres:
        condition: service_healthy
    user: "${UID}:${GID}"
    build:
      context: ./djangoproject
      dockerfile: Dockerfile-dev
    volumes:
      - ./djangoproject:/opt/djangoproject
    working_dir: /opt/djangoproject/djangoapps
    command: python manage.py runserver 0.0.0.0:80 --insecure # --insecure == serve static files
    env_file:
      - ./djangoproject.env
    ports:
      - "127.0.0.1:50500:80"
    networks:
      - ndockerdjango

networks:
  ndockerdjango:
    name: ndockerdjango

volumes:
    vpostgres: {}
